dinngo/protocolink-logics

.changeset/ninety-seas-fry.md, .env.metis, package.json, src/logics/index.ts, src/logics/openocean-v2/configs.ts, src/logics/openocean-v2/index.ts, src/logics/openocean-v2/logic.swap-token.test.ts, src/logics/openocean-v2/logic.swap-token.ts, src/logics/openocean-v2/slippage.test.ts, src/logics/openocean-v2/slippage.ts, src/logics/openocean-v2/tokens/data/metis.json, src/logics/openocean-v2/tokens/index.ts, test/logics/compound-v2/repay.test.ts, test/logics/compound-v2/supply.test.ts, test/logics/compound-v2/withdraw.test.ts, test/logics/compound-v3/borrow.test.ts, test/logics/compound-v3/supply-collateral.test.ts, test/logics/compound-v3/withdraw-collateral.test.ts, test/logics/openocean-v2/swap-token.test.ts
=> Support OpenOceanV2 on Metis

.changeset/four-crabs-change.md, src/logics/aave-v2/logic.repay.ts, src/logics/aave-v3/logic.repay.ts, src/logics/radiant-v2/logic.repay.ts, src/logics/spark/logic.repay.ts
=> fix: change repay tolerance of aave v2, aave v3, radiant v2 and spark

.changeset/twelve-tables-shout.md, src/logics/morphoblue/logic.repay.ts, src/logics/morphoblue/service.ts, test/logics/morphoblue/repay.test.ts
=> fix: Morphoblue repay tokenIn

.changeset/great-boxes-pull.md, .github/workflows/e2e-test-latest.yml, .github/workflows/e2e-test-mainnet-pb.yml, test/logics/aave-v2/withdraw.test.ts, test/logics/uniswap-v3/swap-token.test.ts, test/logics/utility/flash-loan-aggregrator.test.ts
=> fix: uniswap v3 slippage in e2e test

.changeset/chatty-queens-build.md, README.md
=> fix: readme CI link

.changeset/funny-lies-train.md, .env.mainnet, .env.mainnet.pb, .github/workflows/e2e-test-latest.yml, .github/workflows/e2e-test-mainnet-pb.yml, hardhat.config.ts, test/init.ts, test/logics/uniswap-v3/swap-token.test.ts
=> fix: init.ts rpc url

.changeset/fair-shoes-glow.md, src/logics/compound-v3/configs.ts, test/logics/paraswap-v5/swap-token.test.ts
=> fix: compound v3 polygon market id

.changeset/pink-pillows-deliver.md, src/logics/paraswap-v5/logic.swap-token.ts, src/logics/zeroex-v4/logic.swap-token.ts
=> fix: swap token list in Zeroex and Paraswap

.changeset/clever-penguins-kiss.md, src/logics/zeroex-v4/logic.swap-token.ts
=> fix: ZeroEx takerAddress

.changeset/wicked-sloths-notice.md, src/logics/stargate/logic.swap-token.test.ts, src/logics/stargate/logic.swap-token.ts, test/logics/stargate/swap-token.test.ts
=> fix: stargate fee type

.changeset/gold-comics-brush.md, .changeset/old-cameras-sparkle.md, .changeset/witty-hornets-impress.md, src/logics/stargate/configs.ts, src/logics/stargate/logic.swap-token.test.ts, src/logics/stargate/logic.swap-token.ts, test/logics/stargate/swap-token.test.ts
=> Fix Stargate Token List

.changeset/ten-poets-crash.md, src/logics/stargate/configs.ts, src/logics/stargate/tokens/data/metis.json
=> fix: add stargate m.USDT

.changeset/fluffy-bulldogs-rest.md, src/logics/sonne/service.ts
=> fix: add Sonne service

.changeset/angry-clouds-tickle.md, package.json, src/logics/paraswap-v5/configs.ts, src/logics/radiant-v2/configs.ts, src/utils/tokens.ts, yarn.lock
=> feat: add BNB Chain configs to protocols

.changeset/sour-peaches-join.md, src/logics/sonne/logic.borrow.test.ts, src/logics/sonne/logic.borrow.ts, test/logics/sonne/borrow.test.ts
=> fix: remove tokenIn from Sonne BorrowLogicFields

.changeset/breezy-points-pay.md, src/logics/uniswap-v3/tokens/index.ts
=> fix: remove WRAPPED_NATIVE_CURRENCY from Uniswap V3

.changeset/little-lobsters-flow.md, README.md, test/logics/openocean-v2/swap-token.test.ts
=> fix: OpenOcean swap test

.changeset/cool-candles-stare.md, package.json, src/logics/paraswap-v5/logic.swap-token.ts, yarn.lock
=> fix: add takeSurplus to Paraswap V5

.changeset/cuddly-bikes-applaud.md, .changeset/loud-coats-work.md, .changeset/three-seals-relate.md, src/logics/permit2/logic.pull-token.test.ts, src/logics/permit2/logic.pull-token.ts, src/logics/utility/logic.flash-loan-aggregator.ts, src/utils/tokens.ts
=> fix: getTokenList text plain content type

.changeset/fair-pants-check.md, src/logics/compound-v3/logic.withdraw-collateral.ts
=> fix: compound v3 withdraw collateral token list

.changeset/four-insects-destroy.md, src/logics/balancer-v2/logic.flash-loan.ts, src/logics/openocean-v2/logic.swap-token.ts, src/logics/uniswap-v3/logic.swap-token.ts, src/utils/tokens.ts
=> feat: support token list logoUri

.changeset/smooth-scissors-compete.md, src/logics/compound-v2/tokens/data/mainnet.json, src/logics/compound-v3/tokens/data/mainnet.json, src/logics/stargate/tokens/data/mainnet.json, src/logics/uniswap-v3/tokens/data/mainnet.json
=> fix: remove common packages included tokens

.changeset/tasty-students-care.md, src/logics/radiant-v2/configs.ts
=> feat: support radiant v2 on Base

.changeset/two-waves-arrive.md, .env.optimism.pb, .github/workflows/e2e-test-optimism-pb.yml
=> fix: get optimism rpc url from secret

.changeset/purple-wombats-run.md, src/logics/radiant-v2/logic.borrow.test.ts, src/logics/radiant-v2/logic.deposit.test.ts, src/logics/radiant-v2/logic.flash-loan.test.ts, src/logics/radiant-v2/logic.repay.test.ts, src/logics/radiant-v2/logic.withdraw.test.ts, src/logics/radiant-v2/service.test.ts, src/logics/sonne/logic.borrow.test.ts, src/logics/sonne/logic.repay.test.ts, src/logics/sonne/logic.supply.test.ts, src/logics/sonne/logic.withdraw.test.ts, src/logics/utility/logic.flash-loan-aggregator.ts, test/logics/radiant-v2/borrow.test.ts, test/logics/radiant-v2/deposit.test.ts, test/logics/radiant-v2/flash-loan.test.ts, test/logics/radiant-v2/repay.test.ts, test/logics/radiant-v2/withdraw.test.ts, test/logics/sonne/borrow.test.ts, test/logics/sonne/repay.test.ts, test/logics/sonne/supply.test.ts, test/logics/sonne/withdraw.test.ts
=> fix: remove radiant v2 from flashloan aggregator

.changeset/modern-lies-exist.md, src/logics/paraswap-v5/configs.ts
[x] update paraswap token list urls
[x] yarn changeset
=> fix: update paraswap token list urls

.changeset/quiet-chefs-grow.md, src/logics/paraswap-v5/logic.swap-token.ts
[x] yarn changeset
[x] remove JSON.parse after fetching the JSON URL
=> fix: update paraswap token list fetching

.changeset/violet-emus-yell.md, src/logics/radiant-v2/configs.ts, src/logics/radiant-v2/logic.borrow.test.ts, src/logics/radiant-v2/logic.deposit.test.ts, src/logics/radiant-v2/logic.flash-loan.test.ts, src/logics/radiant-v2/logic.repay.test.ts, src/logics/radiant-v2/logic.withdraw.test.ts, src/logics/radiant-v2/service.test.ts, src/logics/utility/logic.flash-loan-aggregator.ts, test/logics/radiant-v2/borrow.test.ts, test/logics/radiant-v2/deposit.test.ts, test/logics/radiant-v2/flash-loan.test.ts, test/logics/radiant-v2/repay.test.ts, test/logics/radiant-v2/withdraw.test.ts
[x] remove radiant arbitrum & bnb configs
[x] enable radiant flashloan aggregator
[x] change test chain from arbitrum to mainnet
[x] yarn changeset
=> fix: reopen radiant ethereum & base, remove arbitrum & bnb configs
